/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CloudIcon: typeof import('./src/components/icons/CloudIcon.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    CodePenLogo: typeof import('./src/components/icons/CodePenLogo.vue')['default']
    CssIcon: typeof import('./src/components/icons/CssIcon.vue')['default']
    DownloadIcon: typeof import('./src/components/icons/DownloadIcon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FormatPrompt: typeof import('./src/components/FormatPrompt.vue')['default']
    Head_portrait: typeof import('./src/components/head_portrait.vue')['default']
    HtmlIcon: typeof import('./src/components/icons/HtmlIcon.vue')['default']
    JsIcon: typeof import('./src/components/icons/JsIcon.vue')['default']
    LoginDialog: typeof import('./src/components/login/LoginDialog.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProjectListDialog: typeof import('./src/components/project/ProjectListDialog.vue')['default']
    RegisterDialog: typeof import('./src/components/login/RegisterDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingDialog: typeof import('./src/components/dialogs/SettingDialog.vue')['default']
    SettingsDialog: typeof import('./src/components/Settings/SettingsDialog.vue')['default']
    SettingsIcon: typeof import('./src/components/icons/SettingsIcon.vue')['default']
    UnifiedButton: typeof import('./src/components/ui/UnifiedButton.vue')['default']
    ViewIcon: typeof import('./src/components/icons/ViewIcon.vue')['default']
  }
}
